[package]
name = "wtvr3d"
version = "0.1.0"
authors = ["John Tiesselune <tiesse@wtvr.rocks>"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.28"
wasm-bindgen = "0.2.51"
nalgebra = "0.18.1"

[dependencies.web-sys]
version = "0.3.28"
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlRenderingContext',
  'WebGlUniformLocation',
  'WebGlProgram',
  'WebGlShader',
  'Window',
]
